---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: route-planner
spec:
  encryptedData:
    token: AgApa1jWz4zfFF0U7GE0BDXOQt0KyBze8WzJenGgHTBr52POP/PgKF4qGk5Ece+EEeCcy3BWHaPkj5UngITvWH5nAnfz2Qo/hYPUkgp3assKuxGHW1KJkvPbkUhzZgowH5UimOrBL8bxJpcIrEUQfKfMZCL9M+jGRtlH703cALOpTOaH8WSCv9rjbyzKMC4x3Ai17yxBtg9cz1BwhJiW/MVE9lB86NzFtFXuCKe3o+JNbgL7Dl2SlyNnaeAcFwZmeME0axBKY2bQqg2sZeFtdk9mhcVrJ52+8D0mP0xK/oveEbVEX1BtpImt8v7HGxC8qdXu/wib8dJ16h5cWWYR8SKoGY3z6ulaq5imHDUGTvHH/qJCeb6fPO20vWQOh1TBCcd1te76yC2NRJHPu3ucOPkN+ERwlSDjMcbIjxsS3YavlGh0hh/9KTVq3FW6yfuh31IJ57ECaBCuY/i2rRy4tTAySbWL6QeupKc6v4a8TumR7ml1Nc3mQbxP4No8JQWa5JiGoeZqbeMXo5Qyh0SvRcO5ZifxKeQhT2ljhH//XXUHnHe4ZK21PrjLJxivOedM9QGVkZekCj9fvvG4R9HeUQa/Y+DiZPaIrdtkMDeAdzgNv4TxaMkM4a+PzCe9yeUA7vJE9McA52UXqXz49I/XNCe9ioqOGTc7GpVzt4sm/kp1IrfHzX3s5scPp1HPA9tluhE6V/23grR9sexTXpuZU6j0yqYaH+yNRkU4W1cVUQN9SkkJUDKlu2w75/sEciC3nv8kWFog0dfHsf/6nNWri0DVNWoH2Ovg2QdmX9j0Sy8OVvDepFKyrxhwtXgvpwhobnekn9QHchcIgc/TAbq4VgsxwsDWRjwjrWSZW6EW9WqvyqroZ416FzJlRCsIYhL9uAwwH/qaxYQ0eLpZajRWcb9NJNSK2znVHlvs/oLxdnUC1cd10rvhWwD1
  template:
    metadata:
      name: tunnel-token
      namespace: route-planner   
