---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: route-planner
spec:
  encryptedData:
    token: AgBIVGtDgNNjjAMlwJPrWKdxjoRH/+VXOtC5EmV3YyCU1FhiolgRuJ82+1a8FbSRmKMRvYmI+gnqmZEfy3W3V4kzwye7qw61rcMuRgfhC6h6liKKjDYZJzyErsOd6wxlY8AWDDQKtd3CxR6gnF1C+jEABkkK67NR00F8qfT+m9sO/kkCAYuvQi9A1I3VQNmLJTO0YWDXPxFLItxWLbSjn6xq3boocHl+ZvcorJIcqmaFmC2kjPF232wBnnLyzPylmpwP4kMWtjdUzOLDmSJio7+lGo2ZORRySrRJkbUxYDwsnjwo/En0bNXVtzD8WJAUj9DsewUSghKtIGK6vXIrfyBj79vxVa25fvuMV1xHocSpC3Eb9RHEStpi0aTbTXoxSFRl2VF3j/QCg5wvK9eMd58TnnSVLaHUUxYmwWOQBXQyjd8nLulQftlNC8UnDw+1hviC/be4f1PfThnZlK2+QJoMj3qqeCG+TsmO6RumHz3Swst3Y1qitDyMMpAxFaSD8bPQvUuxYoYTioGlDVSKQddrd7YfL0PIHOBiFOXRlBxnQwoy507yXK7ysVXCtcfB6pL8JTUO/mCwzpwg6QQvWc4IaRKl+BQ9Zr8OP15Fl6VUsaYuYZRkEQrMfpd5TdNDPoUS/mxGYD4ys1w9iJvpcHSNjOhGnULxpaPeA6ZygFompk4XJ0j56fEjXOCYl/wS3dduhj2GTh3Ki+TEFAwwPohRzuqhQTjKUBBQmX+n5hHzfthMKARy6FjD2CBwzTEIt28F2ruYEB/WrJs2OrHFCQtw5oIt0iyLlzEi8p/4qtZoICgIPU3PDGr744roB4zILxApUE0aRpCWBGyhjtuzRVCqx/uRjgbfpPvS8UpWmC+QejFFN4keClAW06fkKNqkHmpoCFVJC4vYCuvKb/Yo9mPJh5M0YQ8Cq/oCrR1/yCBwd8OxW0kwtkB4
  template:
    metadata:
      name: tunnel-token
      namespace: route-planner
